title: kukuwhy
author: GitHub User
email: kukuwhy6@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  I'm a seasoned security engineer with 6 years in service security, specializing in resolving complex challenges through automation and tooling to optimize processes. With a background as a security consultant for diverse firms, I advocate for a deep comprehension of code and infrastructure among engineers, constantly advancing my knowledge to elevate security standards



show_excerpts: false # set to true to show excerpts on the homepage

paginate: 5
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  # the way how dates should be displayed
  date_format: "%b %-d, %Y"

  # (optional) discqus comment configuration
  # disqus:
  #   shortname: bitbrain-github-io

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://github.com/kukuwhy
      icon: github-square
      color: purple

  # wether the author box should be displayed
  show_author: true

  # the animation speed of the scroll-in effect
  animation_speed: 50

  # wether to enable Right-to-Left support or not
  rtl: false

  # Replaces the default avatar provider (gravatar)
  #avatar_source: github
  github_username: kukuwhy
  #avatar_source: local
  #avatar_path: /assets/avatar.png

# Build settings
theme: jekyll-dash

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - liquid-md5
 - jekyll/tagging
